<IkRpg_Gen>:
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'top'
        BoxLayout:
            orientation: 'vertical'
            TitleBar: 
                id: _title_bar
                size_hint: 1, None
                height: 24

            OptionsBar:
                id: _options_bar
                size_hint: 1, None
                height: 48


    AnchorLayout:
        TabArea:
            id: _tab_area
            size_hint: 1, None